#pragma once

#include <fmod.hpp>
#include <phonon.h>

// Public ABI of Valve's phonon_fmod.dll. The binary SDK does not ship this
// header, so keep the small, stable API surface used by xrSound locally.
enum IPLSpatializerParams
{
    IPL_SPATIALIZE_SOURCE_POSITION,
    IPL_SPATIALIZE_OVERALL_GAIN,
    IPL_SPATIALIZE_APPLY_DISTANCEATTENUATION,
    IPL_SPATIALIZE_APPLY_AIRABSORPTION,
    IPL_SPATIALIZE_APPLY_DIRECTIVITY,
    IPL_SPATIALIZE_APPLY_OCCLUSION,
    IPL_SPATIALIZE_APPLY_TRANSMISSION,
    IPL_SPATIALIZE_APPLY_REFLECTIONS,
    IPL_SPATIALIZE_APPLY_PATHING,
    IPL_SPATIALIZE_HRTF_INTERPOLATION,
    IPL_SPATIALIZE_DISTANCEATTENUATION,
    IPL_SPATIALIZE_DISTANCEATTENUATION_ROLLOFFTYPE,
    IPL_SPATIALIZE_DISTANCEATTENUATION_MINDISTANCE,
    IPL_SPATIALIZE_DISTANCEATTENUATION_MAXDISTANCE,
    IPL_SPATIALIZE_AIRABSORPTION_LOW,
    IPL_SPATIALIZE_AIRABSORPTION_MID,
    IPL_SPATIALIZE_AIRABSORPTION_HIGH,
    IPL_SPATIALIZE_DIRECTIVITY,
    IPL_SPATIALIZE_DIRECTIVITY_DIPOLEWEIGHT,
    IPL_SPATIALIZE_DIRECTIVITY_DIPOLEPOWER,
    IPL_SPATIALIZE_OCCLUSION,
    IPL_SPATIALIZE_TRANSMISSION_TYPE,
    IPL_SPATIALIZE_TRANSMISSION_LOW,
    IPL_SPATIALIZE_TRANSMISSION_MID,
    IPL_SPATIALIZE_TRANSMISSION_HIGH,
    IPL_SPATIALIZE_DIRECT_MIXLEVEL,
    IPL_SPATIALIZE_REFLECTIONS_BINAURAL,
    IPL_SPATIALIZE_REFLECTIONS_MIXLEVEL,
    IPL_SPATIALIZE_PATHING_BINAURAL,
    IPL_SPATIALIZE_PATHING_MIXLEVEL,
    IPL_SPATIALIZE_SIMULATION_OUTPUTS,
    IPL_SPATIALIZE_DIRECT_BINAURAL,
    IPL_SPATIALIZE_DISTANCE_ATTENUATION_RANGE,
    IPL_SPATIALIZE_SIMULATION_OUTPUTS_HANDLE,
    IPL_SPATIALIZE_OUTPUT_FORMAT,
    IPL_SPATIALIZE_NORMALIZE_PATHING_EQ,
    IPL_SPATIALIZE_NUM_PARAMS
};

extern "C"
{
    void F_CALL iplFMODGetVersion(unsigned int* major, unsigned int* minor, unsigned int* patch);
    void F_CALL iplFMODInitialize(IPLContext context);
    void F_CALL iplFMODTerminate();
    void F_CALL iplFMODSetHRTF(IPLHRTF hrtf);
    void F_CALL iplFMODSetHRTFDisabled(bool disabled);
    void F_CALL iplFMODSetSimulationSettings(IPLSimulationSettings settings);
}
