////////////////////////////////////////////////////////////////////////////
//	Module 		: physic_item.h
//	Created 	: 11.02.2004
//  Modified 	: 11.02.2004
//	Author		: Dmitriy Iassenev
//	Description : Physic item
////////////////////////////////////////////////////////////////////////////

#pragma once

#include "gameobject.h"
#include "PHShellCreator.h"
#include "PhysicsShellHolder.h"
class CPhysicItem : public CPhysicsShellHolder, public CPHShellSimpleCreator
{
    typedef CPhysicsShellHolder inherited;

    bool m_use_hud_model_as_world{};
    bool m_auto_generate_collision{true};
    bool m_force_auto_generated_collision{};
    float m_world_model_scale{1.f};
    u32 m_auto_collision_max_boxes{16};
    shared_str m_hud_world_visual;
    mutable Fbox m_scaled_bounding_box;

    void ApplyHudWorldVisual();
    void PlayWorldIdleAnimation();

public:
    bool m_ready_to_destroy;

public:
    CPhysicItem();
    virtual ~CPhysicItem();
    void init();
    virtual void reinit();
    virtual void Load(LPCSTR section);
    virtual void reload(LPCSTR section);
    virtual void OnH_B_Independent(bool just_before_destroy);
    virtual void OnH_B_Chield();
    virtual void UpdateCL();
    virtual BOOL net_Spawn(CSE_Abstract* DC);
    virtual void net_Destroy();
    virtual void activate_physic_shell();
    virtual void setup_physic_shell();
    virtual void create_box_physic_shell();
    virtual void create_box2sphere_physic_shell();
    virtual void create_physic_shell();
    void renderable_RenderUI(u32 context_id, IRenderable* root) override;

    Fmatrix renderable_WorldTransform() const override;
    void Center(Fvector& center) const override;
    float Radius() const override;
    const Fbox& BoundingBox() const override;

    bool UsesHudModelAsWorld() const { return m_use_hud_model_as_world; }
    float WorldModelScale() const { return m_world_model_scale; }
    bool PHUseAutoGeneratedCollision() const override { return m_auto_generate_collision; }
    bool PHForceAutoGeneratedCollision() const override { return m_force_auto_generated_collision; }
    float PHCollisionVisualScale() const override { return m_world_model_scale; }
    u32 PHAutoCollisionMaxBoxes() const override { return m_auto_collision_max_boxes; }
};
