-- Главное меню для Теней Чернобыля.
-- KRodin (c) 2018
-- Выкинул из скрипта всё что связано с мультиплеером и прочий мусор.
-- Исправил утечки памяти из-за неудаления частей меню после его закрытия (см. main_menu:close_and_delete_menu())
-- Сделано специально для использования с движком OGSR.

class "main_menu" (CUIScriptWnd)
function main_menu:__init() super()
	self.mbox_mode = 0
	self:InitControls()
	self:InitCallBacks()
end

function main_menu:__finalize()
	--log1("--main_menu:__finalize() called!")
end

function main_menu:InitControls()
	self:Init(0, 0, 1024, 768)			  
	self:SetAnimationPreset("curve_fade")
	self:SetAnimationTimes(520, 220)
	self:SetAnimationDelay(180)

	local xml = CScriptXmlInit()
	xml:ParseFile("ui_mm_main.xml")

	xml:InitStatic("back_movie", self)
	xml:InitStatic("background", self)
	xml:InitStatic("fire_movie", self)
	self.menu_sound = xml:InitMMSound("menu_sound", self)

	local main_menu_path
	if level.present() then
		if db.actor and not db.actor:alive() then
			main_menu_path = "menu_main_single_dead"
		else
			main_menu_path = "menu_main_single"
		end
	elseif has_valid_last_save() then
		main_menu_path = "menu_main_last_save"
	else
		main_menu_path = "menu_main"
	end

	self.main_buttons = self:InitButtonMenu(xml, main_menu_path, {
		"btn_new_game", "btn_ret", "btn_lastsave", "btn_load", "btn_save",
		"btn_options", "btn_credits", "btn_quit_to_mm", "btn_quit"
	})
	self.new_game_buttons = self:InitButtonMenu(xml, "menu_new_game", {
		"btn_novice", "btn_stalker", "btn_veteran", "btn_master", "btn_new_back"
	})
	self:SetButtonMenu(self.main_buttons)

	self.message_box = CUIMessageBoxEx()
	self:Register(self.message_box, "msg_box")	

	local ver = xml:InitStatic("static_version", self)
	ver:SetText("ver. " .. _G.main_menu.get_main_menu():GetGSVer())
	ver:SetTextColor(255, 255, 0, 0)
end

function main_menu:InitButtonMenu(xml, path, button_names)
	if not xml:NodeExist(path) then
		return nil
	end

	local menu = CUIWindow()
	xml:InitWindow(path, 0, menu)
	menu:SetAutoDelete(true)
	self:AttachChild(menu)

	for _, name in ipairs(button_names) do
		local button_path = path .. ":" .. name
		if xml:NodeExist(button_path) then
			local button = xml:Init3tButton(button_path, menu)
			self:Register(button, name)
		end
	end

	menu:Show(false)
	return menu
end

function main_menu:SetButtonMenu(menu)
	if self.current_button_menu then
		self.current_button_menu:Show(false)
	end

	self.current_button_menu = menu
	if self.current_button_menu then
		self.current_button_menu:Show(true)
	end
end

function main_menu:Show(visible)
	if self.current_button_menu then
		self.current_button_menu:Show(visible)
	end
end

function main_menu:OnButton_new_game_clicked()
	if self.new_game_buttons then
		self:SetButtonMenu(self.new_game_buttons)
	end
end

function main_menu:OnButton_new_back_clicked()
	self:SetButtonMenu(self.main_buttons)
end

function main_menu:InitCallBacks()
	self:AddCallback("btn_new_game", ui_events.BUTTON_CLICKED, self.OnButton_new_game_clicked, self)
	self:AddCallback("btn_new_back", ui_events.BUTTON_CLICKED, self.OnButton_new_back_clicked, self)
	-- new game
	self:Connect("btn_novice",  ui_events.BUTTON_CLICKED, self.StartGame, self, "gd_novice")
	self:Connect("btn_stalker", ui_events.BUTTON_CLICKED, self.StartGame, self, "gd_stalker")
	self:Connect("btn_veteran", ui_events.BUTTON_CLICKED, self.StartGame, self, "gd_veteran")
	self:Connect("btn_master",  ui_events.BUTTON_CLICKED, self.StartGame, self, "gd_master")
	-- options																											
	self:AddCallback("btn_options", ui_events.BUTTON_CLICKED, self.OnButton_options_clicked, self)
	-- load																												
	self:AddCallback("btn_load", ui_events.BUTTON_CLICKED, self.OnButton_load_clicked, self)
	-- save																												
	self:AddCallback("btn_save", ui_events.BUTTON_CLICKED, self.OnButton_save_clicked, self)
	-- quit																												
	self:AddCallback("btn_quit", ui_events.BUTTON_CLICKED, self.OnButton_quit_clicked, self)
	self:AddCallback("btn_quit_to_mm", ui_events.BUTTON_CLICKED, self.OnButton_disconnect_clicked, self)
	self:AddCallback("btn_lastsave", ui_events.BUTTON_CLICKED, self.OnButton_last_save, self)
	self:AddCallback("btn_credits", ui_events.BUTTON_CLICKED, self.OnButton_credits_clicked, self)
	-- message box																										
	self:AddCallback("msg_box", ui_events.MESSAGE_BOX_OK_CLICKED, self.OnMsgOk, self)
	self:AddCallback("msg_box", ui_events.MESSAGE_BOX_CANCEL_CLICKED, self.OnMsgCancel, self)
	self:AddCallback("msg_box", ui_events.MESSAGE_BOX_YES_CLICKED, self.OnMsgYes, self)
	self:AddCallback("msg_box", ui_events.MESSAGE_BOX_NO_CLICKED, self.OnMsgNo, self)
	self:Connect("msg_box", ui_events.MESSAGE_BOX_QUIT_GAME_CLICKED, cmd, "disconnect")
	self:Connect("msg_box", ui_events.MESSAGE_BOX_QUIT_WIN_CLICKED,  cmd, "quit")
	self:AddCallback("btn_ret", ui_events.BUTTON_CLICKED, self.close_and_delete_menu, self)
end

function main_menu:OnMsgOk()
	self.mbox_mode = 0
end

function main_menu:OnMsgCancel()
	self.mbox_mode = 0
end

function main_menu:LoadLastSave()
	cmd("load_last_save")
	self:close_and_delete_menu()
end

function main_menu:OnMsgYes()
	if self.mbox_mode == 1 then
		self:LoadLastSave()	
	end

	self.mbox_mode = 0
end

function main_menu:OnMsgNo()
	self.mbox_mode = 0
end


function main_menu:OnButton_last_save()
	if not level.present() or not ( db.actor_proxy.online and db.actor:alive() ) then
		self:LoadLastSave()
		return
	end

	self.mbox_mode = 1
	self.message_box:Init("message_box_confirm_load_save")
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function main_menu:OnButton_credits_clicked()
	game.start_tutorial("credits_seq")
end

function main_menu:OnButton_quit_clicked()
	self.message_box:Init("message_box_quit_windows")
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function main_menu:OnButton_disconnect_clicked()
	self.message_box:Init("message_box_quit_game")
	self.message_box:SetText("ui_mm_quit_game_message")
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function main_menu:StartGame( difficulty )
	cmd("g_game_difficulty "..difficulty)
	if alife() then
		cmd("disconnect")	
	end
	cmd("start server(all/single/alife/new)")
	self:close_and_delete_menu()
end

function main_menu:OnButton_save_clicked()
	if not self.save_dlg then
		self.save_dlg = ui_mm_save_load_dialog.save_load_dialog( true )
		self.save_dlg.owner = self
	end
	--
	ui_mm_save_load_dialog.fill_savedgames_list(self.save_dlg)
	--
	self:GetHolder():start_stop_menu(self.save_dlg, true)
	self:Show(false)
end

function main_menu:OnButton_load_clicked()
	if not self.load_dlg then
		self.load_dlg = ui_mm_save_load_dialog.save_load_dialog()
		self.load_dlg.owner = self
	end
	--
	ui_mm_save_load_dialog.fill_savedgames_list(self.load_dlg)
	--
	self:GetHolder():start_stop_menu(self.load_dlg, true)
	self:Show(false)
end

function main_menu:OnButton_options_clicked()
	if not self.opt_dlg then
		self.opt_dlg = ui_mm_opt_main.options_dialog()
		self.opt_dlg.owner = self
	end

	self:GetHolder():start_stop_menu(self.opt_dlg, true)
	self:Show(false)
end

function main_menu:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self, dik, keyboard_action)

	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik_to_bind(dik) == key_bindings.kQUIT and self.current_button_menu == self.new_game_buttons then
			self:SetButtonMenu(self.main_buttons)
			return true
		end

		if dik_to_bind(dik) == key_bindings.kQUIT then
			if level.present() and db.actor_proxy.online and db.actor:alive() then
				self:close_and_delete_menu()
			end
		elseif dik == DIK_keys.DIK_N then --personal_test
			xpcall(function() dofile(getFS():update_path("$game_scripts$", "personal_test.lua")) end, log1)
		end
	end

	return true
end

--Для закрытия меню использовать только этот специальный метод!
function main_menu:close_and_delete_menu()
	-- Удаляем в движке каллбеки, в которых хранятся ссылки на объекты оконных классов (которые добавляются в AddCallback(..., self),
	-- иначе части меню не удалятся и будут висеть в памяти до перезапуска LUA (до загрузки сейва, например)
	-- Так же, надо обнулить висячие ссылки (self.*_dlg), иначе сборщик мусора эти объекты не удалит. Да, это странно, но это так.
	if self.save_dlg then self.save_dlg:ClearCallbacks() self.save_dlg = nil end
	if self.load_dlg then self.load_dlg:ClearCallbacks() self.load_dlg = nil end
	if self.opt_dlg then
		if self.opt_dlg.dlg_video_adv then self.opt_dlg.dlg_video_adv = nil end
		self.opt_dlg:ClearCallbacks() self.opt_dlg = nil
	end
	self:ClearCallbacks() --main_menu удаляется движком, но для надёжности и ему каллбеки удалим.
	--
	cmd("main_menu off")
end
